{{- if and (or (eq .Values.installMode "host") (eq .Values.installMode "component")) (has "search" .Values.components) }}
{{- $name := include "karmada.name" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-search
  namespace: {{ include "karmada.namespace" . }}
  labels:
    {{- toYaml .Values.search.labels | nindent 4}}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    {{- include "karmada.search.labels" . | nindent 4}}
{{- end }}
