---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: gitlab
  namespace: {{ .Values.global.environment.name }}
  annotations:
    helm.sh/hook-weight: "-4"
    argocd.argoproj.io/sync-wave: "-4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bootstrap-secret-store

  target:
    name: gitlab
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2

  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: gitlab
