---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: gitlab
  namespace: {{ .Values.global.environment.name }}
  annotations:
    # helm.sh/hook: pre-install
    helm.sh/hook-weight: "-5"
    # helm.sh/hook-delete-policy: before-hook-creation # hook-succeeded
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bootstrap-secret-store

  target:
    name: gitlab
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ "{{" }} .json {{ "}}" }}"

  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: gitlab
