{{- if not (contains .Values.global.environment.name "prod")}}
{{- if .Values.global.environment.dependencies.database.elasticsearch.required }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: elastic-se
  namespace: {{ .Values.global.environment.name }}
spec:
  hosts:
    {{- range .Values.elasticsearch.overrideHosts }}
    - {{.}}
    {{- end }}
  location: MESH_INTERNAL
  ports:
  - number: 1433
    name: TCP
  resolution: DNS
{{- end }}
{{- end }}