{{- if not (contains .Values.global.environment.name "prod")}}
{{- if .Values.global.environment.dependencies.database.mongodb.required }}
apiVersion: batch/v1
kind: Job
metadata:
  name: vault-mongodb-credentials-gen
  namespace: gitlab # {{ .Values.global.environment.name }}
  annotations:
    helm.sh/hook: pre-upgrade,pre-install
    helm.sh/hook-weight: "-4"
    helm.sh/hook-delete-policy: hook-succeeded #? ,hook-failed
    argocd.argoproj.io/sync-wave: "-4"
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 4
  template:
    metadata:
      name: "vault-mongodb-credentials-gen"
    spec:
      restartPolicy: Never
      containers:
        - name: dbcreds
          image: registry.gitlab.com/emergetech/core/devops/secret_helper:0.1.0
          args: 
            - -e
            - {{ .Values.global.environment.name | quote }}
            - -t
            - mongodb
          imagePullPolicy: Always
      imagePullSecrets:
        - name: {{ default "gitlab" ((.Values).pullSecret) }}
{{- end -}}
{{- end }}