{{- if not (contains .Values.global.environment.name "prod")}}
{{ if ((.Values.global).environment.name) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.environment.name }}
  labels:
    istio-injection: enabled
    kubernetes.io/metadata.name: {{ .Values.global.environment.name }}
    ephemeral: "true"
    envType: "ephemeral"
    chartVersion: {{ .Chart.Version }}
  annotations:
    # helm.sh/hook: pre-upgrade,pre-install
    helm.sh/hook-weight: "-6"
    # helm.sh/hook-delete-policy: before-hook-creation # hook-succeeded
    argocd.argoproj.io/sync-wave: "-6"
{{ end }}
{{ end }}