apiVersion: v2
name: emerge-elasticsearch
description: A Helm chart for Kubernetes
type: application
version: 0.0.0

dependencies:
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
