apiVersion: v2
appVersion: "latest"
description: A Helm chart for Kubernetes
name: environment-template
version: 0.0.11

dependencies:
  - name: emerge-mssql
    version: "1.0.6"
    repository: https://charts.emergemarket.io
    condition: global.environment.dependencies.database.mssql.required
  - name: elasticsearch
    version: "7.17.3"
    repository: https://helm.elastic.co
    condition: global.environment.dependencies.database.elasticsearch.required
