global:
  environment: 
    name: devopstest
    dependencies:
      database:
        mssql: 
          required: false
        mongodb:
          required: false
        elasticsearch: 
          required: false

pullSecret: "gitlab"

mongodb:
  resource:
    name: mongodb
    version: 5.0.9
    members: 1
    tls:
      enabled: false
      certificateKeySecretRef: tls-certificate
      caCertificateSecretRef: tls-ca-key-pair
      certManager:
        certDuration: 8760h   # 365 days
        renewCertBefore: 720h   # 30 days

elasticsearch:
  persistence:
    enabled: false
  secret:
    enabled: false
  protocol: http
  maxUnavailable: 0
  overrideHosts: []
  nameOverride: elasticsearch
    


vault:
    secrets: {}