global:
  environment: 
    name: devopstest
    dependencies:
      database:
        mssql: 
          required: false
        mongodb:
          required: false
        elasticsearch: 
          required: false

vault:
    secrets: {}