apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "query-exporter.fullname" . }}
  {{- with .Values.configmapAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    
  labels:
    {{ include "query-exporter.labels" . | nindent 4 }}
data:
 config.yaml: |-
  {{ tpl .Values.exporter_config . | nindent 4 }}
