apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backstage.fullname" . }}-auth
data:
  AUTH_MICROSOFT_CLIENT_ID: {{ .Values.auth.microsoft.clientId }}
  AUTH_MICROSOFT_TENANT_ID: {{ .Values.auth.microsoft.tenantId }}

