{{- if not (contains (include "mssql.env" .) "prod") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mssql-latest.fullname" . }}
  namespace: {{ include "mssql.env" . }}
  labels:
    {{- include "mssql-latest.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      {{- include "mssql-latest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{ include "mssql.pod_annotations" . | indent 8 | trim }}
      labels:
        {{- include "mssql-latest.selectorLabels" . | nindent 8 }}
    spec:
      hostname: {{ split "." (include "mssql.hostname")._0 . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command:
            - /bin/bash
            - -c
            - cp /var/opt/config/mssql.conf /var/opt/mssql/mssql.conf && /opt/mssql/bin/sqlservr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containers.ports.containerPort}}
          env:
           - name: MSSQL_PID
             value: "{{ .Values.MSSQL_PID.value}}"
           - name: ACCEPT_EULA
             value: "{{ .Values.ACCEPT_EULA.value | upper}}"
           - name: MSSQL_AGENT_ENABLED
             value: "{{ .Values.MSSQL_AGENT_ENABLED.value}}"
           - name: SA_PASSWORD
             value: "vault:secrets/EphemeralEnvironment/{{ include "mssql.env" . }}/azsql#password"
          volumeMounts:
           - name: mssqldb
             mountPath: /var/opt/mssql
           - name: mssqluserdb
             mountPath: /var/opt/mssql/userdata
           - name: mssqllog
             mountPath: /var/opt/mssql/userlog
           - name: mssqltemp
             mountPath: /var/opt/mssql/tempdb
           - name: mssql-config-volume
             mountPath: /var/opt/config
      volumes:
       - name: mssqldb
         persistentVolumeClaim:
          claimName: mssql-data
       - name: mssqluserdb
         persistentVolumeClaim:
          claimName: mssql-userdb
       - name: mssqllog
         persistentVolumeClaim:
          claimName: mssql-log
       - name: mssqltemp
         persistentVolumeClaim:
          claimName: mssql-temp          
       - name: mssql-config-volume
         configMap:
          name: mssql-config
{{- end }}