{{- if not (contains (include "mssql.env" .) "prod") }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ include "mssql-latest.fullname" . }}
  namespace: {{ include "mssql.env" . }}
  labels:
  {{- include "mssql-latest.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ include "mssql.hostname" . }}
  location: MESH_INTERNAL
  ports:
  - number: {{ .Values.containers.ports.containerPort}}
    name: TCP
  resolution: DNS
{{- end }}