{{- if not (contains (include "mssql.env" .) "prod") }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-files
  namespace: {{ .Values.global.environment.name }}
provisioner: file.csi.azure.com
volumeBindingMode: Immediate
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - mfsymlinks
  - actimeo=30
parameters:
  skuName: Standard_LRS
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mssql-latest.fullname" . }}-data
  namespace: {{ .Values.global.environment.name }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "azure-files"
spec:
  accessModes:
  - "ReadWriteMany"
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mssql-latest.fullname" . }}-userdb
  namespace: {{ .Values.global.environment.name }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "azure-files"
spec:
  accessModes:
  - "ReadWriteMany"
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mssql-latest.fullname" . }}-log
  namespace: {{ .Values.global.environment.name }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "azure-files"
spec:
  accessModes:
   - "ReadWriteMany"
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mssql-latest.fullname" . }}-temp
  namespace: {{ .Values.global.environment.name }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "azure-files"
spec:
  accessModes:
   - "ReadWriteMany"
  resources:
    requests:
      storage: 5Gi
{{- end }}