{{- if not (contains (include "mssql.env" .) "prod") }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: node-disk
  namespace: {{ include "mssql.env" . }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mssql-latest.fullname" . }}-data
  namespace: {{ include "mssql.env" . }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "node-disk"
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mssql-latest.fullname" . }}-userdb
  namespace: {{ include "mssql.env" . }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "node-disk"
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mssql-latest.fullname" . }}-log
  namespace: {{ include "mssql.env" . }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "node-disk"
spec:
  accessModes:
   - "ReadWriteOnce"
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mssql-latest.fullname" . }}-temp
  namespace: {{ include "mssql.env" . }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "node-disk"
spec:
  accessModes:
   - "ReadWriteOnce"
  resources:
    requests:
      storage: 5Gi
{{- end }}