{{- if false }}
{{- if not (contains (include "mssql.env" .) "prod") }}
apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: {{ .Values.global.environment.name }}
  labels:
    {{- include "mssql-latest.labels" . | nindent 4 }}
type: Opaque
data:
 sa_password : {{ .Values.sa_password | b64enc | quote}}
{{- end }}
{{- end }}
