{{- if not (contains (include "mssql.env" .) "prod") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mssql-latest.fullname" . }}
  namespace: {{ .Values.global.environment.name }}
  labels:
    {{- include "mssql-latest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "mssql-latest.selectorLabels" . | nindent 4 }}
{{- end }}