apiVersion: batch/v1
kind: Job
metadata:
  name: vault-mssql-credentials-gen
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-4"
    helm.sh/hook-delete-policy: hook-succeeded
    argocd.argoproj.io/sync-wave: "-4"
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 4
  template:
    metadata:
      name: "vault-mssql-credentials-gen"
    spec:
      restartPolicy: Never
      containers:
        - name: dbcreds
          image: registry.gitlab.com/emergetech/core/devops/secret_helper:0.1.0
          args: 
            - -e
            - {{ .Values.global.environment.name | quote }}
            - -t
            - azsql
          imagePullPolicy: Always
      imagePullSecrets:
        - name: {{ default "gitlab" ((.Values.deployment).pullSecret) }}