---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mongodb.database.name" . }}
  namespace: {{ .Values.global.environment.name }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mongodb.database.name" . }}
  namespace: {{ .Values.global.environment.name }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
      - delete
      - get

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "mongodb.database.name" . }}
  namespace: {{ .Values.global.environment.name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mongodb.database.name" . }}
roleRef:
  kind: Role
  name: {{ include "mongodb.database.name" . }}
  apiGroup: rbac.authorization.k8s.io
