apiVersion: v1
kind: Secret
metadata:
  name: mongo-admin-secret
  namespace: {{ .Values.global.environment.name }}
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.infra:8200"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
    vault.security.banzaicloud.io/vault-env-daemon: "true"
    vault.security.banzaicloud.io/enable-json-log: "true"
    vault.security.banzaicloud.io/mutate-configmap: "true"
    vault.security.banzaicloud.io/vault-max-retries: "10"
    vault.security.banzaicloud.io/vault-client-timeout: 2m
    vault.security.banzaicloud.io/vault-role: application
data:
  connectionString.standard: {{ list "mongodb://${vault:secrets/data/EphemeralEnvironment/" .Values.global.environment.name "/mongodb/username#value}:${vault:secrets/data/EphemeralEnvironment/" .Values.global.environment.name "/mongodb/password#value}@example-mongodb-0.example-mongodb-svc.mongodb.svc.cluster.local:27017,example-mongodb-1.example-mongodb-svc.mongodb.svc.cluster.local:27017,example-mongodb-2.example-mongodb-svc.mongodb.svc.cluster.local:27017/admin?ssl=true" | join "" | b64enc }}
  connectionString.standardSrv: {{ list "mongodb+srv://${vault:secrets/data/EphemeralEnvironment/" .Values.global.environment.name "/mongodb/username#value}:${vault:secrets/data/EphemeralEnvironment/" .Values.global.environment.name "/mongodb/password#value}@example-mongodb-svc.mongodb.svc.cluster.local/admin?ssl=true" | join "" | b64enc }}
  password: {{ list "vault:secrets/data/EphemeralEnvironment/" .Values.global.environment.name "/mongodb/password#value" | join "" | b64enc }}
  username: {{ list "vault:secrets/data/EphemeralEnvironment/" .Values.global.environment.name "/mongodb/username#value" | join "" | b64enc }}
