{{- if .Values.createOperator }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mongodb.operator.name" . }}
  namespace: {{ .Values.global.environment.name }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if eq (.Values.operator.watchNamespace | default "") "*" }} ClusterRole {{ else }} Role {{ end }}
metadata:
  name: {{ include "mongodb.operator.name" . }}
  namespace: {{ .Values.global.environment.name }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mongodbcommunity.mongodb.com
  resources:
  - mongodbcommunity
  - mongodbcommunity/status
  - mongodbcommunity/spec
  - mongodbcommunity/finalizers
  verbs:
  - get
  - patch
  - list
  - update
  - watch

---
kind: {{ if eq (.Values.operator.watchNamespace | default "") "*" }} ClusterRoleBinding {{ else }} RoleBinding {{ end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "mongodb.operator.name" . }}
  namespace: {{ .Values.global.environment.name }}
subjects:
- kind: ServiceAccount
  name: {{ include "mongodb.operator.name" . }}
  namespace: {{ .Values.global.environment.name }}
roleRef:
  kind: {{ if eq (.Values.operator.watchNamespace | default "") "*" }} ClusterRole {{ else }} Role {{ end }}
  name: {{ include "mongodb.operator.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}