---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    email: devops@emergemarket.com
  labels:
    owner: mongodb
  name: {{ include "mongodb.operator.name" . }}
  namespace: {{ .Values.global.environment.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ include "mongodb.operator.name" . }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: {{ include "mongodb.operator.name" . }}
    spec:
      securityContext:
        runAsUser: 2000
        runAsNonRoot: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - {{ include "mongodb.operator.name" . }}
              topologyKey: kubernetes.io/hostname
      containers:
        - command:
            - /usr/local/bin/entrypoint
          env:
            {{- if .Values.operator.extraEnvs }}
            {{ toYaml .Values.operator.extraEnvs | nindent 12 }}
            {{- end }}
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: {{ include "mongodb.operator.name" . }}
            - name: AGENT_IMAGE
              value: "{{ .Values.registry.agent }}/{{ .Values.agent.name }}:{{ .Values.agent.version }}"
            - name: VERSION_UPGRADE_HOOK_IMAGE
              value: "{{ .Values.registry.versionUpgradeHook }}/{{ .Values.versionUpgradeHook.name }}:{{ .Values.versionUpgradeHook.version }}"
            - name: READINESS_PROBE_IMAGE
              value: "{{ .Values.registry.readinessProbe }}/{{ .Values.readinessProbe.name }}:{{ .Values.readinessProbe.version }}"
            - name: MONGODB_IMAGE
              value: {{ .Values.mongodb.name }}
            - name: MONGODB_REPO_URL
              value: {{ .Values.mongodb.repo }}
          image: {{ .Values.registry.operator }}/mongodb-kubernetes-operator:{{ .Values.operator.version }}
          imagePullPolicy: {{ .Values.registry.pullPolicy}}
          name: {{ include "mongodb.operator.name" . }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          securityContext:
            runAsUser: 2000
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      serviceAccountName: {{ include "mongodb.operator.name" . }}
